version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: dev
      MINIO_ROOT_PASSWORD: devdevdev
    volumes:
      - ./docker-manifest.json:/tmp/manifests/docker-manifest.json
    entrypoint: 'sh'
    command:
      -c "mkdir -p /data/manifests && cp /tmp/manifests/docker-manifest.json /data/manifests/manifest.json && minio server /data --console-address ':9001'"

  launcher:
    build:
      context: ./launcher
    ports:
      - 3000:3000
    environment:
      REACT_APP_HMT_ADDRESS: "0x1f613bc2f4e741EA96d30A5957fF7fA6916acDD6"
      REACT_APP_ESCROW_FACTORY_ADDRESS: "0x161228DaAB6F935548E2B98f6cedC9FF648C781d"
      REACT_APP_REC_ORACLE_ADDRESS: "0x61F9F0B31eacB420553da8BCC59DC617279731Ac"
      REACT_APP_REP_ORACLE_ADDRESS: "0xD979105297fB0eee83F7433fC09279cb5B94fFC6"
      REACT_APP_EXCHANGE_ORACLE_ADDRESS: "0x6b7E3C31F34cF38d1DFC1D9A8A59482028395809"
    command: ["yarn", "start-prod"]

  exchange:
    build:
      context: ./exchange
    ports:
      - 3001:3000
    command: ["yarn", "start-prod"]

  recording-oracle:
    build:
      context: ./recording-oracle
    network_mode: "host"
    environment:
      ETH_PRIVATE_KEY: 486a0621e595dd7fcbe5608cbbeec8f5a8b5cabe7637f11eccfc7acd408c3a0e
      ETH_HTTP_SERVER: https://data-seed-prebsc-1-s1.binance.org:8545
      PORT: 3005
    command: ["yarn", "start"]

  reputation-oracle:
    build:
      context: ./reputation-oracle
    ports:
      - 3006:3006
    environment:
      ETH_PRIVATE_KEY: 657b6497a355a3982928d5515d48a84870f057c4d16923eb1d104c0afada9aa8
      ETH_HTTP_SERVER: https://data-seed-prebsc-1-s1.binance.org:8545
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: dev
      MINIO_SECRET_KEY: devdevdev
      MINIO_BUCKET_NAME: job-results
      PORT: 3006
    command: ["yarn", "start"]
