version: '3.7'

services:
  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    command: node /app/ganache-core.docker.cli.js --noVMErrorsOnRPCResponse --db=/ganache_data -m goat -i 1337 --hostname 0.0.0.0 --unlock 0x1413862c2b7054cdbfdc181b83962cb0fc11fd92 -g 1000 -v
    ports:
      - 8547:8545

  minio:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: dev
      MINIO_ROOT_PASSWORD: devdevdev
    volumes:
      - ./docker-manifest.json:/tmp/manifests/docker-manifest.json
    entrypoint: 'sh'
    command:
      -c "mkdir -p /data/manifests && cp /tmp/manifests/docker-manifest.json /data/manifests/manifest.json && minio server /data --console-address ':9001'"

  launcher:
    build:
      context: ./launcher
    ports:
      - 3000:3000
    environment:
      REACT_APP_HMT_ADDRESS: "0x444c45937D2202118a0FF9c48d491cef527b59dF"
      REACT_APP_ESCROW_FACTORY_ADDRESS: "0x3FF93a3847Cd1fa62DD9BcfE351C4b6BcCcF10cB"
      REACT_APP_REC_ORACLE_ADDRESS: "0x61F9F0B31eacB420553da8BCC59DC617279731Ac"
      REACT_APP_REP_ORACLE_ADDRESS: "0xD979105297fB0eee83F7433fC09279cb5B94fFC6"
      REACT_APP_EXCHANGE_ORACLE_ADDRESS: "0x6b7E3C31F34cF38d1DFC1D9A8A59482028395809"
    command: ["yarn", "start-prod"]

  exchange:
    build:
      context: ./exchange
    ports:
      - 3001:3000
    command: ["yarn", "start-prod"]

  recording-oracle:
    build:
      context: ./recording-oracle
    network_mode: "host"
    environment:
      ETH_PRIVATE_KEY: 486a0621e595dd7fcbe5608cbbeec8f5a8b5cabe7637f11eccfc7acd408c3a0e
      ETH_HTTP_SERVER: http://localhost:8547
      PORT: 3005
    command: ["yarn", "start"]

  reputation-oracle:
    build:
      context: ./reputation-oracle
    ports:
      - 3006:3006
    environment:
      ETH_PRIVATE_KEY: 657b6497a355a3982928d5515d48a84870f057c4d16923eb1d104c0afada9aa8
      ETH_HTTP_SERVER: http://ganache:8545
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: dev
      MINIO_SECRET_KEY: devdevdev
      MINIO_BUCKET_NAME: job-results
      PORT: 3006
    command: ["yarn", "start"]
